name: sockssl-server

services:
    server:
        image: sockssl-server
        restart: always
        ports:
            - "443:443"
        environment:
            - LOG_LEVEL=${LOG_LEVEL}
            - PASSWORD=${PASSWORD}
            - TARGET_HOST=nginx

    nginx:
        image: nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf